[package]
name = "biodivine-pbn-control"
version = "0.3.2"
description = "A library for controlling parametrized Boolean networks."
authors = ["Samuel Pastva <daemontus@gmail.com>, Eva Smijakova <smijakova.eva@gmail.com>"]
edition = "2021"
license = "MIT"
exclude = [
    "auxiliary_scripts/*",
    "models/*",
    "results/*"
]

[dependencies]
serde_json = "1.0"
itertools = "0.14"
chrono = "0.4"
biodivine-lib-bdd = "0.6"
biodivine-lib-param-bn = "0.6"

[features]
# Allows to enable Z3 solver inside lib-param-bn. We don't normally need this,
# but sometimes (in particular AEON.py), we need lib-param-bn with Z3 enabled.
solver-z3 = ["biodivine-lib-param-bn/solver-z3"]

[dev-dependencies]

# Enable rich docs for some online docs autogen services.
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./res/docs-head.html"]
