[package]
name = "biodivine-pbn-control"
version = "0.2.0"
description = "A library for controlling parametrized Boolean networks."
authors = ["Samuel Pastva <daemontus@gmail.com>, Eva Smijakova <smijakova.eva@gmail.com>"]
edition = "2021"
license = "MIT"
exclude = [
    "auxiliary_scripts/*",
    "models/*",
    "results/*"
]

[dependencies]
rayon = "1.3.0"
clap = "4.0.26"
serde_json = "1.0.59"
itertools = "0.10.1"
chrono = "0.4.19"
biodivine-lib-bdd = "0.4.*"
biodivine-lib-param-bn = { git = "https://github.com/sybila/biodivine-lib-param-bn.git", branch =  "dev-faster-reach" }

[dev-dependencies]

[features]
print_progress = []

# Enable rich docs for some online docs autogen services.
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./res/docs-head.html"]
